// <auto-generated />
using System;
using GameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Migrations
{
    [DbContext(typeof(netContext))]
    partial class netContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Entities.Rendelesek", b =>
                {
                    b.Property<int>("Rendelesek_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Rendelesek_ID"));

                    b.Property<DateOnly>("Rendeles_datuma")
                        .HasColumnType("date");

                    b.Property<string>("Vasarlo_ID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fizetesi_mod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("szallitasi_mod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("termek_ID")
                        .HasColumnType("int");

                    b.HasKey("Rendelesek_ID");

                    b.ToTable("rendelesek");
                });

            modelBuilder.Entity("GameStore.Entities.Termekek", b =>
                {
                    b.Property<int>("Jatek_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Jatek_ID"));

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kiado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mufaj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Raktarkeszlet")
                        .HasColumnType("int");

                    b.Property<decimal>("akcios_ar")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ar")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("korhatar_besorolas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("leiras")
                        .HasColumnType("int");

                    b.Property<DateTime>("megjelenesi_datum")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Jatek_ID");

                    b.ToTable("termekek");
                });

            modelBuilder.Entity("GameStore.Entities.Vasarlok", b =>
                {
                    b.Property<int>("Vasarlo_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Vasarlo_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("szallitasi_cim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefonszam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Vasarlo_ID");

                    b.ToTable("vasarlok");
                });
#pragma warning restore 612, 618
        }
    }
}
